swagger: "2.0"
info:
  title: NodeJsLab04
  description: My server for Lab04
  version: 1.0.0
host: "localhost:3000"
basePath: "/api"
tags:
- name: "Orders"
  description: "Everything about your Buyer"
- name: "Shop"
  description: "Everything about your Shop"
- name: "General"
  description: "General commands"
schemes:
- "http"
paths:
  /buyer:
    get:
      tags:
        - "Orders"
      summary: Returns a list of buyer's orders.
      operationId: "getOrders"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: A JSON array of buyer info
          schema: 
            $ref: "#/definitions/Orders"
  /shop:
    get:
      tags:
        - "Shop"
      summary: Returns an orders of shop.
      operationId: "getShop"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: A JSON array of shop info
          schema: 
            $ref: "#/definitions/Shop"
  /neworder:
    post:
      tags:
      - "Orders"
      summary: "Add a new order to the buyer's list"
      description: ""
      operationId: "addOrder"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Order object that needs to be added to the list of buyer"
        required: true
        schema:
          $ref: "#/definitions/Orders"
      responses:
        405:
          description: "Invalid input"
  /cancord:
    post:
      tags:
      - "Orders"
      summary: "Cancel an order to the list of buyer"
      description: ""
      operationId: "cancOrder"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Order object that needs to be canceled to the list of buyer"
        required: true
        schema:
          $ref: "#/definitions/Orders"
      responses:
        405:
          description: "Invalid input"
  /newcost:
    put:
      tags:
      - "General"
      summary: "Update an existing orders"
      description: ""
      operationId: "updateOrder"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cost of order that needs to be updated to the list of buyer"
        required: true
        schema:
          $ref: "#/definitions/NewCost"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Order not found"
        405:
          description: "Validation exception"
definitions:
  Shop:
    type: "object"
    properties:
      id_byuer:
        type: "integer"
        format: "int32"
      id_order:
        type: "integer"
        format: "int32"
    xml:
      name: "Shop"
  Orders:
    type: "object"
    properties:
      id_order:
        type: "integer"
        format: "int32"
      order_date:
        type: "string"
        format: "date-time"
      order_cost:
        type: "integer"
        format: "int32"
    xml:
      name: "Orders"
  CancelOrder:
    type: "object"
    properties:
      id_order:
        type: "integer"
        format: "int32"
  NewCost:
    type: "object"
    properties:
      id_order:
        type: "integer"
        format: "int32"
      cost:
        type: "integer"
        format: "int32"
